# Setup
title:            Seongjin Choi
tagline:          'A Jekyll theme'
description:      'Transportation and deep learning researcher in KAIST'
url:              https://benchoi93.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
